config/routes.rb
Rails.application.routes.draw do
  apipie
  resources :servers
  get 'servers/:id/processes', to: 'servers#show_processes'
  root 'servers#index'

end

app/models/attribute_history.rb
class AttributeHistory
  include Mongoid::Document

  include Mongoid::Timestamps
  field :attribute_name
  field :attribute_value
  # field :created_at, :type => DateTime

  embedded_in :server, :inverse_of => :attribute_histories
end

app/models/server.rb
class Server
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name
  field :instance_id
  field :ip_address
  field :ssh_user
  field :cpu_usage, type: Float
  field :disk_usage, type: Float

  embeds_many :attribute_histories
  validates_uniqueness_of :name, :instance_id, :ip_address

  before_update :save_attribute_history

  def save_attribute_history
    self.attribute_histories.create!({:attribute_name => 'cpu_usage',
                                                        :attribute_value => self.cpu_usage,
                                                        :created_at => Time.now})
    self.attribute_histories.create!({:attribute_name => 'disk_usage',
                                                        :attribute_value => self.disk_usage,
                                                        :created_at => Time.now})
  end

  def cpu_usage_history
    self.attribute_histories.select{|h| h['attribute_name']=='cpu_usage'}.last(10)
  end

  def disk_usage_history
    self.attribute_histories.select{|h| h['attribute_name']=='disk_usage'}.last(10)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_filter  :verify_authenticity_token

end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :set_server, only: [:show, :show_processes, :edit, :update, :destroy]

  # GET /servers
  # GET /servers.json
  api :GET, '/servers.json'
  description 'Get all servers
  [
      {
          "id": {
              "$oid": "5749310343c6572eba000001"
          },
          "name": "Second Server",
          "instance_id": "id2",
          "ip_address": "hytjuyk",
          "cpu_usage": null,
          "disk_usage": null,
          "url": "http://localhost:3000/servers/5749310343c6572eba000001.json"
      },
      {
          "id": {
              "$oid": "5749317943c6572eba000002"
          },
          "name": "3rd_server",
          "instance_id": "hvgwjkkdc",
          "ip_address": "62.2.2n2.",
          "cpu_usage": 1.2,
          "disk_usage": 86,
          "url": "http://localhost:3000/servers/5749317943c6572eba000002.json"
      },
      {
          "id": {
              "$oid": "5749ad2143c6574aba000002"
          },
          "name": "FOurth",
          "instance_id": "ugghjknml",
          "ip_address": "hbnm",
          "cpu_usage": null,
          "disk_usage": null,
          "url": "http://localhost:3000/servers/5749ad2143c6574aba000002.json"
      },
      {
          "id": {
              "$oid": "5749b13443c6574aba000003"
          },
          "name": "fift_server",
          "instance_id": "hvgwdc",
          "ip_address": "52.33.139.194",
          "cpu_usage": null,
          "disk_usage": null,
          "url": "http://localhost:3000/servers/5749b13443c6574aba000003.json"
      },
      {
          "id": {
              "$oid": "574af46143c657dfa4000000"
          },
          "name": "ytghj",
          "instance_id": "gvghbj",
          "ip_address": "hgvhjbn1a",
          "cpu_usage": null,
          "disk_usage": null,
          "url": "http://localhost:3000/servers/574af46143c657dfa4000000.json"
      }
  ]'
  def index
    @servers = Server.all
  end

  # GET /servers/1
  # GET /servers/1.json
  api :GET, '/servers/{:id}.json'
  description 'Get server with id = params[:id]'
  def show
  end

  def show_processes
    processes = `ssh #{@server.ssh_user}@#{@server.ip_address} ps aux`
    @processes = processes.split(" ")
  end

  # GET /servers/new
  def new
    @server = Server.new
  end

  # GET /servers/1/edit
  def edit
  end

  # POST /servers
  # POST /servers.json
  api :POST, '/servers.json'
  description 'Create new server'
  def create
    @server = Server.new(server_params)

    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, notice: 'Server was successfully created.' }
        format.json { render :show, status: :created, location: @server }
      else
        format.html { render :new }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servers/1
  # PATCH/PUT /servers/1.json
  api :PUT, '/servers/{:id}.json'
  description 'Update server with id = param[:id]'
  def update
    respond_to do |format|
      @server.ip_address
      if @server.update(server_params)
        format.html { redirect_to @server, notice: 'Server was successfully updated.' }
        format.json { render :show, status: :ok, location: @server }
      else
        format.html { render :edit }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server.destroy
    respond_to do |format|
      format.html { redirect_to servers_url, notice: 'Server was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_server
      @server = Server.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def server_params
      params.require(:server).permit(:name, :instance_id, :ip_address, :ssh_user, :cpu_usage, :disk_usage)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CloudWatch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/servers/_form.html.erb
<%= form_for(@server) do |f| %>
    <% if @server.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@server.errors.count, "error") %> prohibited this server from being saved:</h2>

          <ul>
            <% @server.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :instance_id %><br>
      <%= f.text_field :instance_id %>
    </div>
    <div class="field">
      <%= f.label :ip_address %><br>
      <%= f.text_field :ip_address %>
    </div>
    <div class="field">
      <%= f.label :ssh_user %><br>
      <%= f.text_field :ssh_user %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/servers/edit.html.erb
<h1>Editing Server</h1>

<%= render 'form' %>

<%= link_to 'Show', @server %> |
<%= link_to 'Back', servers_path %>

app/views/servers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Servers</h1>

<table border="1">
  <thead>
    <tr>
      <th>Name</th>
      <th>InstanceId</th>
      <th>IpAddress</th>
      <th>Cpu Usage</th>
      <th>Disk Usage(in %)</th>
      <th>last Updated</th>
      <th>Created On</th>

      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @servers.each do |server| %>
      <tr>
        <td><%= server.name %></td>
        <td><%= server.instance_id %></td>
        <td><%= server.ip_address %></td>
        <td><%= server.cpu_usage %></td>
        <td><%= server.disk_usage %></td>
        <td><%= server.updated_at %></td>
        <td><%= server.created_at %></td>
        <td><%= link_to 'Show', server %></td>
        <td><%= link_to 'Edit', edit_server_path(server) %></td>
        <td><%= link_to 'Destroy', server, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <!--<td><a class="metrics-lnk" href="">Show metrics</a></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Server', new_server_path %>

app/views/servers/new.html.erb
<h1>New Server</h1>

<%= render 'form' %>

<%= link_to 'Back', servers_path %>

app/views/servers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @server.name %>
</p>

<p>
  <strong>Instance:</strong>
  <%= @server.instance_id %>
</p>

<p>
  <strong>IpAddress:</strong>
  <%= @server.ip_address %>
</p>

<p>
  <strong>Cpu usage:</strong>
    <table border="1">
        <thead>
            <tr>
            <%@server.cpu_usage_history.each do |history|%>
              <td>
                <%=history['created_at']%>
              </td>
            <%end%>
            </tr>
        </thead>
      <tbody>
      <tr>
        <%@server.cpu_usage_history.each do |history|%>
            <td>
              <%=history['attribute_value'].presence || "no data"%>
            </td>
        <%end%>
      </tr>

      </tbody>
    </table>
</p>

<p>
  <strong>Data usage:</strong>
<table border="1">
  <thead>
  <tr>
    <%@server.disk_usage_history.each do |history|%>
        <td>
          <%=history['created_at']%>
        </td>
    <%end%>
  </tr>
  </thead>
  <tbody>
  <tr>
    <%@server.disk_usage_history.each do |history|%>
        <td>
          <%=history['attribute_value'].presence || "no data"%>
        </td>
    <%end%>
  </tr>

  </tbody>
</table>
</p>


<%= link_to 'Edit', edit_server_path(@server) %> |
<%= link_to 'Back', servers_path %>

<p>

  <a href="/servers/<%= @server.id%>/processes/">
    <button>Show Processes Running:
    </button>
  </a>
</p>

app/views/servers/show_processes.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @server.name %>
</p>
<%= link_to 'Back', "/servers/#{@server.id}" %>
<p>
  <strong>Processes:</strong>
</p>
    <% i=0 %>
    <% while (i < @processes.length) do%>
    <p>
      <% cur_i = 1%>
      <%  while(cur_i%12 != 0) do %>
          <%= @processes[i] %>
          <%cur_i+=1%>
          <%i+=1%>
      <%end%>
    </p>
    <%end%>